language: python
python:
  - '3.8'

# safelist
branches:
  only:
    - master

before_install:
#  - pipenv install
   - deactivate
   - pwd
   - ls -a
   - pipenv shell

services:
  - postgresql

#env: DJANGO_SETTINGS_MODULE=pure_beurre_django.settings


script: 
  #-  travis_wait 30 ./manage.py test
  #- ./manage.py test
  #- ./manage.py test.tests_integration
  - ./manage.py test.tests_models
  #- ./manage.py test.tests_parcours_utilisateur
  #- ./manage.py test.tests_vues
