language: python
python:
  - '3.8'

branches:
  only:
    - master
    

before_install:
   - sudo apt-get update
   - sudo apt-get install firefox
   

install:
   - pip3 install --upgrade setuptools
   - pip3 install -r requirements.txt
   - pip3 install python-secrets
   - pip3 install django-secrets

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=pure_beurre_django.travis_settings


script: 
  - ./manage.py test substitutor.tests
