language: python
python:
  - '3.8'

# safelist
branches:
  only:
    - master

before_script:
  - pipenv install
  - pipenv shell

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=pure_beurre_django.settings.travis


script: 
  - ./manage.py test.tests_auxilliaries
  - ./manage.py test.tests_integration
  - ./manage.py test.tests_models
  - ./manage.py test.tests_parcours_utilisateur
  - ./manage.py test.tests_vues
