language: python
python:
  - '3.8'

# safelist
branches:
  only:
    - master

before_script:
  - pipenv install
  - pipenv shell

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=pure_beurre_django.settings.travis

install: travis_wait 30 mvn install

script:
  - ./manage.py test
