language: python
python:
  - '3.8'

# safelist
branches:
  only:
    - staging

#before_script:
#  - pipenv shell

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=disquaire_project.settings.travis

script:
  - ./manage.py test
