# Generated by Django 3.1.2 on 2020-10-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("adresse_mail", models.EmailField(max_length=200)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantite", models.CharField(max_length=255)),
                ("marque", models.TextField()),
                ("nom_categories", models.TextField()),
                ("labels", models.TextField()),
                ("ingredients", models.TextField()),
                ("produits_provoqu_allergies", models.TextField()),
                ("traces_eventuelles", models.TextField()),
                ("nutriscore", models.CharField(max_length=255)),
                ("lien_o_ff", models.TextField()),
                (
                    "categorie",
                    models.ManyToManyField(
                        blank=True, related_name="produit", to="substitutor.Categorie"
                    ),
                ),
                (
                    "magasin",
                    models.ManyToManyField(
                        blank=True, related_name="produit", to="substitutor.Store"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recherche", models.CharField(max_length=200)),
                ("date_engistrement", models.DateTimeField(auto_now_add=True)),
                (
                    "substitut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="substitutor.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="substitutor.account",
                    ),
                ),
            ],
        ),
    ]
