# Generated by Django 3.1.2 on 2020-10-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("substitutor", "0003_auto_20201021_0051")]

    operations = [
        migrations.AlterField(
            model_name="product", name="code", field=models.BigIntegerField(null=True)
        )
    ]
