# Generated by Django 3.1.4 on 2020-12-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutor', '0007_product_nom_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='date_insertion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_insertion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='date_insertion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date_engistrement',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
