# Generated by Django 3.1.2 on 2020-10-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("substitutor", "0005_auto_20201027_1603")]

    operations = [
        migrations.AddField(
            model_name="product", name="nutriments", field=models.TextField(null=True)
        )
    ]
